# Generated by Django 4.1.6 on 2023-04-02 17:38

import base.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), base.utils.validate_nonzero]),
        ),
    ]
