# Generated by Django 4.1.6 on 2023-03-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cartitems_remove_cart_cart_items_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
