# Generated by Django 4.1.6 on 2023-04-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(default=5, max_length=10),
        ),
    ]
