# Generated by Django 4.1.6 on 2023-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_max_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_quantity',
            field=models.PositiveIntegerField(default=5, max_length=10),
        ),
    ]
